# Generated by Django 5.1.1 on 2024-11-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_pma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
