# Generated by Django 4.2.16 on 2024-12-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra_pma', '0003_userprofile_is_common'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_common',
        ),
    ]
