# Generated by Django 5.1.1 on 2024-10-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_user'),
        ('events', '0002_file'),
    ]

    operations = [
    ]
