# Generated by Django 5.1.1 on 2024-11-14 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_file_description_file_keywords_file_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requested_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
